---
title: "Logistic Regression Fundamentals"
---

## Introduction
Logistic regression is an important tool for anyone who needs to answer research
questions involving binary outcomes or to make predictions involving the
classification of observations. It is used widely in a whole host of disciplines
including medical research, ecology and the social sciences. The purpose of this
guide is to walk you through the process of learning the main concepts behind
logistic regression: what kinds of questions it can be applied to, how to 
implement a logistic regression model in R and more advanced concepts like
model selection and cross-validation.

## Prerequisites
This guide on logistic regression assumes that you are already familiar with the
basic theory and interpretation of simple and multiple linear regression models
and know how to fit them using the `lm()` function in R. Knowledge of how to
identify confounders and mediators and how they impact attempts at causal 
inference is also helpful. See 
[Effects Models - Dealing with Confounders](confounders.html) and 
[Mediators in Effects Models](mediators.html) for introductions to these 
concepts if they are new to you.

## Guide Structure
This guide is broken down into 5 stages:

1) The [Foundation](logistic-regression-foundations.html): The fundamental concepts of logistic regression are explained through the lens of a very simple model.
2) Estimating an Effect: Building on the foundation, we take a look at causal inference using data from the Framingham Heart Study.
3) Prediction: If prediction is the goal, then the considerations and model selection process is different to that of an effect size model.
4) Cross-validation: For the prediction model from state 3, we can use cross validation to understand how will this model will perform on data it wasn't trained on.

Let's [get started](logistic-regression-foundations.html)!